name: Test & Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  tests:
    name: Executar testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar libs
        run: |
          pip install -r requirements-dev.txt

      - name: Executar testes
        run: pytest -v

  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' &&
      success()

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar libs
        run: |
          pip install -r requirements.txt

      - name: validacao da instalacao
        run: |
          python - << 'EOF'
          import fastapi
          print("FastAPI OK")
          EOF

      - name: Build
        run: docker build -t app-exemplo .
